server.port=8888

spring.datasource.url=jdbc:sqlserver://containers-us-west-XX.railway.app:14321;databaseName=railway;encrypt=true
spring.datasource.username=railway
spring.datasource.password=seninPasswordun
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
